[package]
name = "client"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "client"
path = "main.rs"

[dependencies]
tunnel-lib = { path = "../tunnel-lib" }
tokio = { version = "1", features = ["full"] }
quinn = "0.10"
rustls = "0.21"
tokio-rustls = "0.24"
webpki-roots = "0.25"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
bincode = "1.3"
clap = { version = "4.4", features = ["derive"] }
uuid = { version = "1", features = ["v4"] }
httparse = "1.1"
bytes = "1.5"
dashmap = "6.1.0"
futures = "0.3"
hyper = { version = "0.14", features = ["client", "http1", "http2", "runtime"] }
hyper-util = { version = "0.1", features = ["client-legacy", "http1", "http2"] }
http-body-util = "0.1"
hyper-rustls = { version = "0.24", features = ["rustls-native-certs", "http1", "http2"] }
 
