[package]
name = "tunnel-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.9"
prost = "0.11"
prost-types = "0.11"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
hyper = "0.14"
uuid = { version = "1", features = ["v4"] }
chrono = "0.4"
futures = "0.3"
url = "2"

[build-dependencies]
tonic-build = "0.9" 
prost = "0.11"
prost-types = "0.11" 