[package]
name = "server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"
path = "main.rs"

[dependencies]
tunnel-lib = { path = "../tunnel-lib", features = ["warmup", "egress"] }
tokio = { version = "1", features = ["full"] }
quinn = "0.10"
rustls = "0.21"
tokio-rustls = "0.24"
webpki-roots = "0.25"
serde_yaml = "0.9"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
bincode = "1.3"
clap = { version = "4.4", features = ["derive"] }
dashmap = "6.1.0" # Keep dashmap for managing connected clients
bytes = "1.5"
async-trait = "0.1"
httparse = "1.1"
uuid = { version = "1", features = ["v4"] }
hyper = { version = "0.14", features = ["client", "http1", "http2", "runtime"] }
hyper-rustls = { version = "0.24", features = ["rustls-native-certs", "http1", "http2"] }