[package]
name = "server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"
path = "main.rs"

[dependencies]
tunnel-lib = { path = "../tunnel-lib" }
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
tonic = "0.9"
hyper = "0.14"
hyper-rustls = "0.24"
uuid = { version = "1", features = ["v4"] }
chrono = "0.4"
futures = "0.3"
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
lazy_static = "1.4"
once_cell = "1.18"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "json"] }
function_name = "0.3"
dashmap = "6.1.0"
async-trait = "0.1"
tokio-util = "0.7"

[build-dependencies]
tonic-build = "0.9"
prost = "0.11"
prost-types = "0.11" 