# Client Configuration

log_level: "info"
trace_enabled: false

# Connection to server address and port
server_addr: "127.0.0.1"
server_port: 10086

# Client group id
client_group_id: "group-a"

# Optional: Authentication token
auth_token: "your-token-here"

# Optional: Set to enable HTTP listener
http_entry_port: 8003
# Optional: Set to enable gRPC listener
# grpc_entry_port: 8004
# Optional: Set to enable WSS listener
# wss_entry_port: 8443

